version: '3'
services:
  # Go Application Service
  go-app:
    environment:
      - DATABASE_URL=mongodb://mongo:27017/test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081" 
    depends_on:
      - mongo

  # MongoDB Service
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    image: mongo
    ports:
      - "27017:27017"
    restart: always
